### PR TITLE
Adding data files  for California

### PR DESCRIPTION
**Pull request by avpeery**
### Why:
This code on this branch makes some important changes to the cba tool by @icebreakers-ours . Is it possible to merge these files to master?

### CODE REVIEW

**Comment by derins** [comment]
Thanks for pointing this branch out @avpeery , is it possible to get some more context on what these files are so I know what's going on?

**Comment by gcezar** [comment]
I'd say if there are no impacts on other parts of the code you guys have worked on then I'd say yes, merge it to master. I'm almost sure that the changes are only to the CBA tool in which case we should be fine.

**Comment by jongoncalves** [comment]
I think generally my preference is to have data files like these, especially this amount, in S3. 
We can move forward for now, but an improvement we should add in later.

**Comment by avpeery** [comment]
Thanks for giving this a look! We can discuss about S3 improvement during the meeting today. This version of the CBA tool compared to the version that is used in SCRIPT now is required to run the cost benefit analysis on different load forecast profiles. The current one right now only works for the basecase.

**Review by derins — APPROVED** [review]

**Comment by avpeery** [comment]
I am trying to implement just the All_California case with this code on a separate branch. There are some missing files that need to be addressed before merging to master, or implementing S3

**Comment by icebreakers-ours** [comment]
Hi Team,

Thanks for following up on this. Agreed that I don’t believe the code is fully functional at the moment. I am in the process of making some final updates to this code, and will let the group know when I have finished up.

Thank you

Robbie

**Pull request closed without merging**
